version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app/backend
      - media_volume:/app/backend/media
      - static_volume:/app/backend/static
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3

volumes:
  media_volume:
  static_volume: